/**
 * @file About.cpp
 * @brief implementation of the About dialog for the UI
 */

#include "About.h"
#include "JS8_Main/revision_utils.h"
#include "ui_About.h"

#include <QString>

CAboutDlg::CAboutDlg(QWidget *parent) : QDialog(parent), ui(new Ui::CAboutDlg) {
    ui->setupUi(this);
    setWindowTitle("About JS8Call");
    ui->labelTxt->setText(QString(
        "<h3>%1</h3><br/ >"
        "Build %2 on %3 by %4@%5<br />"
        "<h3>JS8CALL-CN 3.0.1-CN-Beta1（内测版）升级说明</h3>"
        "<p align='left'>JS8CALL-CN 是 JS8Call v3.0.1 的中文本地化版本。本内测版面向定向邀约的 HAM，用于实测中文界面在真实环境下的可用性。</p>"
        "<p align='left'><strong>【设计原则】</strong><br/>"
        "原则是尽可能与原版能力共存：仅在 JS8Call 既有能力之上追加中文支持，不替代原版、不改动 JS8 核心协议与帧结构；与原版同频共存、互不干扰，标准（非中文）通联完全互通。</p>"
        "<p align='left'><strong>【本版已中文化内容】</strong><br/>"
        "- 设置 / 配置对话框：全面中文化<br/>"
        "- 瀑布窗（WideGraph）：控制 / 显示 / 时序 三个标签页<br/>"
        "- 主菜单<br/>"
        "- 定向消息回显：收到的中文定向消息以中文显示<br/>"
        "- 中文消息收发：中文文本经空口收发（ILC 编码）</p>"
        "<p align='left'><strong>【与原版的兼容性】</strong><br/>"
        "- 基于 JS8Call v3.0.1，沿用 JS8 协议与传输帧，未改动调制、同步与时序<br/>"
        "- 与标准 JS8Call 同频共存、互不干扰；CQ、定向等标准（非中文）通联与原版互通<br/>"
        "- 中文消息经 ILC 编码封装在既有帧内：标准 JS8Call 能收到该信号，但因不具备中文码本，显示的是未还原的原始内容，而非可读中文<br/>"
        "- 收发双方均需运行 JS8CALL-CN 才能互发中文</p>"
        "<p align='left'><strong>【特别提示：词库需随正式版同步更新】</strong><br/>"
        "- 本内测版所用的中文词库（ILC 码本）为早期版本，正式版发布后将更新。<br/>"
        "- 词库更新后，必须同步更新到新版词库，中文内容才能正确显示。<br/>"
        "- 收发双方需使用相同版本的词库；任一方未更新，对方的中文都将无法正确还原。<br/>"
        "- 正式版发布后，请务必及时更新词库。</p>"
        "<p align='left'><strong>【已知限制（本版不处理，欢迎反馈但暂不即修）】</strong><br/>"
        "- 部分二级 / 右键菜单仍含英文（如瀑布右键滤波子菜单）<br/>"
        "- 以下专业缩写按惯例保留英文、非遗漏：QSY、TCP、API、CQ、HB、SNR、EN、CAT、USB、PTT、NORMAL、SLOW</p>"
        "<p align='left'><strong>【后续计划】</strong><br/>"
        "- 中继、转发、离开自动回复、网页操作、中文词库进一步优化</p>"
        "<p align='left'><strong>【Windows 安装与运行】</strong><br/>"
        "- 下载安装程序（.exe），双击按提示安装<br/>"
        "- 本版安装程序已自含全部依赖；预期无需另装运行库。若启动报缺 DLL，请将弹窗中的具体文件名反馈给我们<br/>"
        "- 某些联网功能（如 PSK Reporter / spotting）若不工作，也请反馈</p>"
        "<p align='left'><strong>【关于与许可】</strong><br/>"
        "- 由 BG7IPB （<a href=\"mailto:BG7IPB@Hotmail.com\">BG7IPB@Hotmail.com</a>）基于 JS8Call 二次开发；中文词库部分工作及前期的大量测试工作主要由 BG2ALB 完成<br/>"
        "- 依据 GPLv3 许可，源代码公开<br/>"
        "- 本版为非官方改版，未经 JS8Call 官方团队（JS8Call-Improved）认可或背书，目前仅作为中文能力的试验性版本<br/>"
        "- 感谢 JS8Call 原作者 Jordan Sherer（KN4CRD）、JS8Call-Improved 社区团队，以及上游 FT8 / WSJT-X 项目团队</p>"
        "<hr/>"
        "<h3>About the JS8Call Development Team</h3>"
        "<p align='left'>JS8Call is now being developed by the team that "
        "continued development of the original "
        "js8call starting in late 2024.<br />This team includes: <br />Chris "
        "AC9KH, Allan W6BAZ, "
        "Wyatt KJ4CTD, Joe K0OG, Andreas DJ3EI, Rob K4RWR, Jordan KN4CRD.<br "
        "/><br />"
        "The JS8Call code can be downloaded at "
        "<a "
        "href=\"https://github.com/JS8Call-improved/JS8Call-improved\">https://"
        "github.com/"
        "JS8Call-improved/JS8Call-improved</a> .<br /><br />"
        "Legal Notice:<br />"
        "JS8Call 2.4 and later uses libraries from the FFmpeg project under "
        "the LGPLv2.1</p>"
        "<h3>What is JS8Call?</h3>"
        "<p align='left'>JS8Call is a derivative of the WSJT-X application, "
        "restructured and redesigned for message passing. <br/>"
        "It is not supported by nor endorsed by the WSJT-X "
        "development group. <br/>JS8Call is "
        "licensed under and in accordance with the terms "
        "of the <a href=\"https://www.gnu.org/licenses/gpl-3.0.txt\">GPLv3 "
        "license</a>.<br/>"
        "The source code modifications are public and can be found in <a "
        "href=\"https://github.com/js8call/js8call\">this "
        "repository</a>.<br/><br/>"

        "JS8Call is heavily inspired by WSJT-X, Fldigi and FSQCall and would "
        "not exist without the hard work<br />"
        "and dedication of the many developers in the amateur radio "
        "community.<br /><br />"
        "JS8Call stands on the shoulder of giants...the takeoff angle is "
        "better up there.<br /><br />"
        "A special thanks goes out to:<br/><br/><strong>"
        "KC9QNE, "
        "KI6SSI, "
        "K0OG, "
        "LB9YH, "
        "M0IAX, "
        "N0JDS, "
        "OH8STN, "
        "VA3OSO, "
        "VK1MIC, "
        "W0FW, "
        "W6BAZ,</strong><br/><br/>"
        "and the many other amateur radio operators who have helped bring "
        "JS8Call into the world.</p>"
    ).arg(program_title(), GITSHORT, CREATED, UNAME, MACHINE));
}

CAboutDlg::~CAboutDlg() {}
